language: generic
os: osx

env:
  global:
    - PATH=/usr/local/bin:$PATH
    - CURL="curl -fsSkL --max-time 10 --retry 10 --retry-delay 10"
  matrix:
    - EMACS_VERSION=24.4
    - EMACS_VERSION=24.5
    - EMACS_VERSION=25.1
    - EMACS_VERSION=25.2
    - EMACS_VERSION=25.3
    - EMACS_VERSION=26.1
    - EMACS_VERSION=nightly

matrix:    
    allow_failures:
      - env: EMACS_VERSION=nightly

install:
  - |
    if [ $EMACS_VERSION == "nightly" ]; then
        EMACS_BUNDLE=$($CURL http://emacsformacosx.com/builds | grep -oE -m1 "href=\"/emacs-builds/Emacs-20\d{2}[^\"]*dmg" | sed 's/^href="\/emacs-builds\///');
    else
        EMACS_BUNDLE=Emacs-${EMACS_VERSION}-universal.dmg;
    fi
    $CURL -O https://emacsformacosx.com/emacs-builds/${EMACS_BUNDLE}
    hdiutil attach ${EMACS_BUNDLE}
    sudo ln -s /Volumes/Emacs/Emacs.app/Contents/MacOS/Emacs /usr/local/bin/emacs

script:
  make
